name: Test and Upload Results
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -race -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -v ./...
      - name: Test with the Go CLI
        run: go test -race -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -v ./...
      - name: Upload analysis result
        uses: actions/upload-artifact@v3
        with:
          name: analysis-result
          path: log/*.json
      - name: Upload deprecated log
        uses: actions/upload-artifact@v3
        with:
          name: deprecated-log
          path: log/*.log
